apiVersion: v1
kind: Service
metadata:
  name: fishing-frontend-service
  namespace: fishing-ns
spec:
  selector:
    # Kierowanie ruchu do podów frontendu.
    app: fishing-frontend
  ports:
    - protocol: TCP
      port: 4200       # Port serwisu
      targetPort: 80   # Port kontenera (Nginx nasłuchuje na 80)
  type: ClusterIP