apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: fishing-ingress
  namespace: fishing-ns
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  rules:
    - host: brilliantapp.zad
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: fishing-backend-service
                port:
                  number: 5000
          - path: /auth
            pathType: Prefix
            backend:
              service:
                name: fishing-backend-service
                port:
                  number: 5000
          - path: /
            pathType: Prefix
            backend:
              service:
                name: fishing-frontend-service
                port:
                  number: 4200