apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: db-policy
  namespace: fishing-ns
spec:
  podSelector:
    matchLabels:
      app: fishing-shop-db
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: fishing-backend
        - podSelector:
            matchLabels:
              app: fishing-seeder
      ports:
        - protocol: TCP
          port: 27017

---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: backend-policy
  namespace: fishing-ns
spec:
  podSelector:
    matchLabels:
      app: fishing-backend
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - ports:
        - protocol: TCP
          port: 5000
  egress:
    - to:
        - podSelector:
            matchLabels:
              app: fishing-shop-db
      ports:
        - protocol: TCP
          port: 27017
    - ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53

---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: seeder-policy
  namespace: fishing-ns
spec:
  podSelector:
    matchLabels:
      app: fishing-seeder
  policyTypes:
    - Egress
  egress:
    - to:
        - podSelector:
            matchLabels:
              app: fishing-shop-db
      ports:
        - protocol: TCP
          port: 27017
    - ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53

---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: frontend-policy
  namespace: fishing-ns
spec:
  podSelector:
    matchLabels:
      app: fishing-frontend
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - ports:
        - protocol: TCP
          port: 80
  egress:
    - ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53