# POLITYKA SIECIOWA DLA BAZY DANYCH
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: db-policy
  namespace: fishing-ns
spec:
  # Polityka dotyczy Podów z etykietą 'fishing-shop-db'.
  podSelector:
    matchLabels:
      app: fishing-shop-db
  policyTypes:
    - Ingress
  # Zdefiniowano reguły dla ruchu przychodzącego (Ingress):
  # Baza akceptuje połączenia tylko od Backendu oraz Joba Seedera.
  # Każdy inny ruch (np. z Frontendu lub innych Podów) jest blokowany.
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: fishing-backend
        - podSelector:
            matchLabels:
              app: fishing-seeder
      ports:
        - protocol: TCP
          port: 27017

---
# POLITYKA SIECIOWA DLA BACKENDU
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: backend-policy
  namespace: fishing-ns
spec:
  podSelector:
    matchLabels:
      app: fishing-backend
  policyTypes:
    - Egress
  # Reguły dla ruchu wychodzącego (Egress):
  egress:
    # Zezwolono na połączenie do bazy danych na porcie 27017.
    - to:
        - podSelector:
            matchLabels:
              app: fishing-shop-db
      ports:
        - protocol: TCP
          port: 27017
    # Zezwolono na ruch do serwera DNS (wymagane do rozwiązywania nazw hostów).
    - ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53

---
# POLITYKA SIECIOWA DLA FRONTENDU
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: frontend-policy
  namespace: fishing-ns
spec:
  podSelector:
    matchLabels:
      app: fishing-frontend
  policyTypes:
    - Egress
  # Frontend ma zablokowany wszelki ruch wychodzący,
  # z wyjątkiem zapytań DNS
  egress:
    - ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53