apiVersion: apps/v1
kind: Deployment
metadata:
  name: fishing-backend
spec:
  replicas: 1 # Na start wystarczy 1 kopia
  selector:
    matchLabels:
      app: fishing-backend
  template:
    metadata:
      labels:
        app: fishing-backend
    spec:
      containers:
        - name: backend
          image: fishing-backend:v1
          imagePullPolicy: Never # WAŻNE: To mówi Minikube, żeby brał obraz lokalny, a nie szukał w Internecie
          ports:
            - containerPort: 5000
          env:
            # Pobieramy zwykłe zmienne z ConfigMap
            - name: SALT
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: SALT
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: PORT
            # Pobieramy tajne zmienne z Secret
            - name: DB
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: db_connection
            - name: JWTPRIVATEKEY
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: jwt_key
---
apiVersion: v1
kind: Service
metadata:
  name: fishing-backend-service
spec:
  selector:
    app: fishing-backend
  ports:
    - protocol: TCP
      port: 5000 # Port wewnątrz klastra
      targetPort: 5000 # Port kontenera
  type: ClusterIP # Na razie tylko wewnątrz klastra