apiVersion: apps/v1
kind: Deployment
metadata:
  name: fishing-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fishing-frontend
  template:
    metadata:
      labels:
        app: fishing-frontend
    spec:
      containers:
        - name: frontend
          image: fishing-frontend:v1
          imagePullPolicy: Never
          ports:
            - containerPort: 80 # ZMIANA: Nginx nasłuchuje na 80
---
apiVersion: v1
kind: Service
metadata:
  name: fishing-frontend-service
spec:
  selector:
    app: fishing-frontend
  ports:
    - protocol: TCP
      port: 4200 # Zostawiamy 4200 "na zewnątrz" serwisu, żeby pasowało do Ingressa
      targetPort: 80 # ZMIANA: Ruch trafia do kontenera na port 80
  type: ClusterIP