apiVersion: v1
# Ten obiekt Secret służy do bezpiecznego przechowywania danych logowania do bazy.
kind: Secret
metadata:
  name: mongo-secret
  # Przestrzeń nazw dla zasobu Secret.
  namespace: fishing-ns
type: Opaque
data:
  # Wartości zostały zakodowane do formatu Base64.
  # Komenda użyta w terminalu: echo -n 'admin' | base64
  username: YWRtaW4=
  # Komenda użyta w terminalu: echo -n 'password123' | base64
  password: cGFzc3dvcmQxMjM=