apiVersion: v1
# ConfigMap przechowuje konfigurację, która nie jest poufna.
# W tym przypadku jest to numer portu aplikacji.
kind: ConfigMap
metadata:
  name: backend-config
  namespace: fishing-ns
data:
  PORT: "5000"