apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: fishing-ns
type: Opaque
data:
  db_connection: bW9uZ29kYjovL2FkbWluOnBhc3N3b3JkMTIzQGZpc2hpbmctc2hvcC1kYjoyNzAxNy9maXNoaW5nX3Nob3A/YXV0aFNvdXJjZT1hZG1pbg==
  jwt_key: dHdval9iYXJkem9fdGFqbnlfa2x1Y3pfMTIz
  salt: MTA=