apiVersion: v1
kind: Service
metadata:
  name: fishing-backend-service
  namespace: fishing-ns
spec:
  selector:
    app: fishing-backend
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: ClusterIP